### ISSUE TITLE
Client side implementation

### ISSUE THREAD

**Issue by SaschaJohn** [frapa/bs4-selectbox#1]
Hello @frapa , as far as I see, this is a serverside component for nodejs.
Is it possible to make adjustment to run it directly from a html page in browser?

Thanks in advance 

Sascha

**Comment by frapa** [comment]
Hi @SaschaJohn, this component odds meant to be used with angularjs. Hadn't you checked out the [documentation](https://frapa.github.io/bs4-selectbox-example/dist/index.html)?

If you are not using angularjs you can use another library like selectize.

**Comment by SaschaJohn** [comment]
@frapa sorry to bother you with my questions. I didn't use an "external" directive before.
I also checked your documentation and sample page.
Unfortunately everything is bundled to https://frapa.github.io/bs4-selectbox-example/dist/app.bundle.js

I use angularjs on my page. I tried to script include your resources in my html file.

<head>
       <script src="bs4-selectbox.module.js"></script>
    <script src="bs4-selectbox.directive.js"></script>
    <link rel="stylesheet" href="bs4-selectbox.css" />
</head>

Browser can't include because of the require statements. I removed them and added the html template directly to the bs4-selectbox.directive.js.
I also translated bs4-selectbox.directive.js via babel to plain old js.

Afterwards I had at least something that appered on my webpage. But I think I'm wrong to include the directive like this?

**Comment by frapa** [comment]
@SaschaJohn Yes that is wrong and you are right the documentation is not good in this regard. You can find an example in this repo (where it is included and works properly): https://github.com/frapa/bs4-selectbox-example/.

Basically you have to require the module in your code and add it to the dependencies of your app module, you do not need to manually import it like that int the HTML. For example:

```
require('bs4-selectbox');

angular.module('app', ['bs4-selectbox'])
```

And then it should work in your templates as expected.

**Comment by frapa** [comment]
I am closing this as it seems to be solved.
